spring.application.name=alumnoapirest

# DataSource MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/alumnodb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=56457977Ac

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
